version: "3.8"                                          # file version
services:
  convenience-store-recommendation-redis:                        # service name
    container_name: convenience-store-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: hwnaginkyu42/convenience-store-recommendation-redis
    ports:
      - "6379:6379"
  convenience-store-recommendation-database:
    container_name: convenience-store-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: hwnaginkyu42/convenience-store-recommendation-database
    environment:
      - MARIADB_DATABASE=convenience-store-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"      # container outer : inner
  convenience-store-recommendation-app:
    container_name: convenience-store-recommendation-app
    build: .
    depends_on:          # DB, REDIS 실행 후 WEB 실행
      - convenience-store-recommendation-database
      - convenience-store-recommendation-redis
    image: hwnaginkyu42/convenience-store-recommendation-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always